import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Almarai} from "next/font/google"
import Navbar from "./layotComponant/navbar";

const almarai=Almarai({subsets:["arabic"],weight:["300","400","700","800"]})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  ${almarai.className}`}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
